# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/earth/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),earth)

$(call add-radio-file-sha1-checked,radio/gz.img,ce41a66fd462cc2cc41b4189e7d3a710de15aa02)
$(call add-radio-file-sha1-checked,radio/lk.img,ce7bd17559fe14b3c80f900492a6955a589ae074)
$(call add-radio-file-sha1-checked,radio/logo.img,36b7f553e5dc68a9bcc7496a309070e590227e0f)
$(call add-radio-file-sha1-checked,radio/md1img.img,b4f2fd4b8d7e729b3f45734803a3fcb09a2a2738)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,0b5a14c215d2f05d5b08a98908b014a143ad5053)
$(call add-radio-file-sha1-checked,radio/scp.img,1abbe78dcd29229ebe0f3ec6ebd0aa711e0a2964)
$(call add-radio-file-sha1-checked,radio/spmfw.img,2d1012eb3925a1d8c1a37919ad033a883d8aecf8)
$(call add-radio-file-sha1-checked,radio/sspm.img,adc2689975138ffca5dd875a5aea4d8d58a73061)
$(call add-radio-file-sha1-checked,radio/tee.img,78b49b4e716fdad9ae9055c858b18ca6437abf9f)

endif
